### ISSUE TITLE
Feature: Daily currency.

### ISSUE THREAD

**Issue by PostMoe** [Nekorooni/Kiara#13]
Some command to allow users to pick up a bit of currency on a 24 hour basis.

**Comment by Galakey** [comment]
Adding on to this, make it a random number between 1-10 gold, same as what's gained per leveling. Could use ~daily or something similar.

**Comment by Galakey** [comment]
hmmm don't think it matters that much

**Comment by Nekorooni** [comment]
Added in 010f9ab449b71a0cf15370f909ea50462010d894
