### ISSUE TITLE
Bug: Begone images.

### ISSUE THREAD

**Issue by PostMoe** [Nekorooni/Kiara#18]
On one of my begones the image is bugged and just shows an empty embed. Can't seem to find a way to delete the image in question. Some way to purge all of them and re-upload?

**Comment by Connor-Harkness** [comment]
In Progress of rewriting this class, should be updated soon<sup>tm</sup>

**Comment by Connor-Harkness** [comment]
Ok, so awaiting the PR to be reviewed, but its been rewritten now, so yay #40
