### ISSUE TITLE
Feature: Shop layout / commands

### ISSUE THREAD

**Issue by Galakey** [Nekorooni/Kiara#23]
Change ~buy to ~shop, which opens an embed with sub categories. 

First will be 'Colours', second will be 'Coming soon'. 

~shop colours will open the current menu that opens with ~buy

~buy will be used for actually buying the colours

**Comment by Galakey** [comment]
Adding on, using ~colours **or** ~colors will show a list of all colours a user owns.

**Comment by Nekorooni** [comment]
There is support for multiple shops now, but the ~shop command combines the two shops currently.
