### ISSUE TITLE
Updated Colour Prices

### ISSUE THREAD

**Issue by Galakey** [Nekorooni/Kiara#24]
Cold Winter Breeze - 45g
Brilliant Bronze - 45g
Twilight - 45g
Journey - 45g
Love Is In The Air - 60g
The Light Of A Soul That Will Never Fade - 60g 
Burning Passion - 60g
Seductive Embrace - 60g
A Story Untold - 60g
Reflections Of A Day Long Gone - 60g
A Darkness Only Seen Within - 100g
Spring Petal Dancing In The Mist - 100g
Lost In The Orchid Garden - 100g
Look Into The Stars - 100g
Valentine’s Rose - 100g (February Only)
Walkin’ On A Sunset - 100g

**Comment by Nekorooni** [comment]
Added to ~shop/~buy in 010f9ab449b71a0cf15370f909ea50462010d894
