### ISSUE TITLE
Image compatibility with ~say

### ISSUE THREAD

**Issue by Galakey** [Nekorooni/Kiara#26]
Pls?

**Comment by Nekorooni** [comment]
Should be there, is it not working?

**Comment by Nekorooni** [comment]
Problem was how fast discord deletes the image from their servers.

Your message got deleted before it attempts to download the attachment.
But this depends on how fast they delete the image.

Now it deletes after downloading, as a result your message might stay a bit longer before it's deleted while it downloads the image.
